package business.rules;

import org.arpit.java2blog.model.*;
import java.util.*;

rule "Test Rule - 1" 
no-loop
when
	ruleSetup: RuleSetup( $ruleAccount: account ) 
	orderLine : OrderLine($orderAccount : account)  
    
    ruleAccount: Account() from $ruleAccount
	value : Account(columnValue.equals(ruleAccount.getColumnValue() ) 
					&& columnName.equals(ruleAccount.getColumnName())) 
				from $orderAccount  
				  
then
	System.out.println("\ncolumnKey: " + value.getColumnName() + "\ncolumnValue: " + value.getColumnValue() +
	 	"\nrule number: " + ruleSetup.getRuleNumber());

	modify(orderLine){
		getRulesQualified().add(ruleSetup);
	}
	
end


rule "Test Rule - 3"
when
	orderLine : OrderLine($rulesQualified : rulesQualified)
	rules: RuleSetup() from $rulesQualified
	
then
	System.out.println("RuleQualified_" + rules.getRuleNumber() 
		+ " for OrderLine_" + orderLine.getOrderLineNumber());	  
	
end

/*
rule "Test Rule - 2"
no-loop
when
	$ruleMap: RuleMap($ruleMaps : ruleMapObj)
	$orderMap: OrderMap($orderMaps : orderMapObj)
	
	Map.Entry( $ruleKey: key, $ruleValue: value ) from $ruleMaps.entrySet()
	tempRuleMap : Map() from $ruleValue
	Map.Entry( $columnKey: key, $columnValue: value ) from tempRuleMap.entrySet()
	
	Map.Entry( $orderKey: key, $orderValue: value ) from $orderMaps.entrySet()
	tempOrderMap : Map() from $orderValue
	
	Map.Entry( $columnKey == key && $columnValue == value ) from tempOrderMap.entrySet()
	

then
	System.out.println("\ncolumnKey: " + $columnKey + "\ncolumnValue: " + $columnValue + "\nrule number: " + $ruleKey);
	
end
*/