package business.rules;

import org.arpit.java2blog.model.*;
import java.util.*;

rule "Test Rule - 1" 
no-loop
when
	ruleSetup: RuleSetup( $ruleAccount: account ) 
	orderLine : OrderLine($orderAccount : account)  
    
    ruleAccount: Account() from $ruleAccount
	value : Account(columnValue.equals(ruleAccount.getColumnValue() ) 
					&& columnName.equals(ruleAccount.getColumnName())) 
				from $orderAccount  
				  
then
	System.out.println("\ncolumnKey: " + value.getColumnName() + "\ncolumnValue: " + value.getColumnValue() +
	 	"\nrule number: " + ruleSetup.getRuleNumber());

	modify(orderLine){
		getRulesQualified().add(ruleSetup);
	}
	
end


